oc delete -f kube/mongo.yaml
oc delete -f kube/stix_gen_config.yaml
oc delete -f kube/mongo_svc.yaml
oc delete -f kube/stix_gen_api.yaml
oc delete -f kube/stix_gen_route.yaml
oc delete -f kube/stix_gen_svc.yaml
oc delete -f kube/stix_gen_ui.yaml
oc delete -f kube/stix_gen_ui_route.yaml
oc delete -f kube/stix_gen_ui_svc.yaml
oc delete project stix-gen